{% set version = "1.2.12" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-refmanager
  version: {{ version|replace("-", "_") }}

source:
  fn: RefManageR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/RefManageR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RefManageR/RefManageR_{{ version }}.tar.gz
  sha256: 7736f479b80b05c5479b3121e27dec5c16cd5f830dab5bcd983e3ba67050ddc1

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testthat
requirements:
  host:
    - r-base
    - r-bibtex >=0.4.1
    - r-httr
    - r-jsonlite
    - r-lubridate >=1.5.0
    - r-plyr
    - r-stringr
    - r-xml2

  run:
    - r-base
    - r-bibtex >=0.4.1
    - r-httr
    - r-jsonlite
    - r-lubridate >=1.5.0
    - r-plyr
    - r-stringr
    - r-xml2

test:
  commands:
    - $R -e "library('RefManageR')"           # [not win]
    - "\"%R%\" -e \"library('RefManageR')\""  # [win]

about:
  home: https://github.com/ropensci/RefManageR/
  license: GPL-2 | GPL-3 | BSD_3_clause
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
  summary: Provides tools for importing and working with bibliographic references. It greatly
    enhances the 'bibentry' class by providing a class 'BibEntry' which stores 'BibTeX'
    and 'BibLaTeX' references, supports 'UTF-8' encoding, and can be easily searched
    by any field, by date ranges, and by various formats for name lists (author by last
    names, translator by full names, etc.). Entries can be updated, combined, sorted,
    printed in a number of styles, and exported. 'BibTeX' and 'BibLaTeX' '.bib' files
    can be read into 'R' and converted to 'BibEntry' objects. Interfaces to 'NCBI Entrez',
    'CrossRef', and 'Zotero' are provided for importing references and references can
    be created from locally stored 'PDF' files using 'Poppler'. Includes functions for
    citing and generating a bibliography with hyperlinks for documents prepared with
    'RMarkdown' or 'RHTML'.
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
